const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, 'src', 'i18n', 'locales', 'ar.json');
const enPath = path.join(__dirname, 'src', 'i18n', 'locales', 'en.json');

const arJson = JSON.parse(fs.readFileSync(arPath, 'utf8'));
const enJson = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// The mapping dictionaries
const translations = {
    "failedToLoadData": { ar: "فشل تحميل البيانات", en: "Failed to load data" },
    "revenue": { ar: "الإيرادات", en: "Revenue" },
    "visitors": { ar: "الزوار", en: "Visitors" },
    "salesDistribution": { ar: "توزيع المبيعات", en: "Sales Distribution" },
    "conversionFunnel": { ar: "مسار التحويل", en: "Conversion Funnel" },
    "topProducts": { ar: "أفضل المنتجات", en: "Top Products" },
    "seeAll": { ar: "عرض الكل", en: "See All" },
    "noSalesPeriod": { ar: "لا توجد مبيعات في هذه الفترة", en: "No sales in this period" },
    "sale": { ar: "تخفيض", en: "Sale" },
    "stockAlerts": { ar: "تنبيهات المخزون", en: "Stock Alerts" },
    "lessThan": { ar: "أقل من", en: "Less than" },
    "edit": { ar: "تعديل", en: "Edit" },
    "remainingQuantity": { ar: "الكمية المتبقية", en: "Remaining Quantity" },
    "hourlyOrderDistribution": { ar: "توزيع الطلبات بالساعة", en: "Hourly Order Distribution" },
    "analytics": { ar: "التحليلات", en: "Analytics" },
    "retinolSerum": { ar: "مصل الريتينول", en: "Retinol Serum" },
    "basedOnPreviousPurchases": { ar: "بناءً على عمليات الشراء السابقة", en: "Based on previous purchases" },
    "arganOil": { ar: "زيت الأرجان", en: "Argan Oil" },
    "bestSeller": { ar: "الأكثر مبيعاً", en: "Best Seller" },
    "collagenMask": { ar: "قناع الكولاجين", en: "Collagen Mask" },
    "newProductLabel": { ar: "منتج جديد", en: "New Product" },
    "returning": { ar: "عائد", en: "Returning" },
    "new": { ar: "جديد", en: "New" },
    "atRisk": { ar: "في خطر", en: "At Risk" },
    "inactive": { ar: "غير نشط", en: "Inactive" },
    "failedToLoadCustomers": { ar: "فشل تحميل العملاء", en: "Failed to load customers" },
    "anonymousCustomer": { ar: "عميل مجهول", en: "Anonymous Customer" },
    "notSpecified": { ar: "غير محدد", en: "Not Specified" },
    "customerProfile": { ar: "ملف العميل", en: "Customer Profile" },
    "totalSpent": { ar: "إجمالي الإنفاق", en: "Total Spent" },
    "orderCount": { ar: "عدد الطلبات", en: "Order Count" },
    "qualityPoints": { ar: "نقاط الجودة", en: "Quality Points" },
    "contactInfo": { ar: "معلومات الاتصال", en: "Contact Info" },
    "cityNotSpecified": { ar: "المدينة غير محددة", en: "City Not Specified" },
    "aiRecommendations": { ar: "توصيات الذكاء الاصطناعي", en: "AI Recommendations" },
    "customers": { ar: "العملاء", en: "Customers" },
    "searchCustomerPlaceholder": { ar: "البحث عن عميل...", en: "Search customer..." },
    "noResults": { ar: "لا توجد نتائج", en: "No Results" },
    "pleaseEnterCodeAndValue": { ar: "يرجى إدخال الكود والقيمة", en: "Please enter code and value" },
    "couponCreated": { ar: "تم إنشاء الكوبون", en: "Coupon Created" },
    "deleteCouponTitle": { ar: "حذف الكوبون", en: "Delete Coupon" },
    "deleteCouponConfirm": { ar: "هل أنت متأكد من حذف هذا الكوبون؟", en: "Are you sure you want to delete this coupon?" },
    "percentageDiscount": { ar: "خصم كنسبة مئوية", en: "Percentage Discount" },
    "discountAmountPrefix": { ar: "قيمة الخصم", en: "Discount Amount" },
    "usedLabel": { ar: "مستخدم", en: "Used" },
    "expired": { ar: "منتهي", en: "Expired" },
    "expiresLabel": { ar: "ينتهي", en: "Expires" },
    "manageCoupons": { ar: "إدارة الكوبونات", en: "Manage Coupons" },
    "noActiveCoupons": { ar: "لا توجد كوبونات نشطة", en: "No Active Coupons" },
    "addNewCoupon": { ar: "إضافة كوبون جديد", en: "Add New Coupon" },
    "couponCodePlaceholder": { ar: "كود الكوبون", en: "Coupon Code" },
    "percentageType": { ar: "نسبة مئوية", en: "Percentage" },
    "fixedAmountType": { ar: "مبلغ ثابت", en: "Fixed Amount" },
    "valuePercentagePlaceholder": { ar: "قيمة النسبة", en: "Percentage Value" },
    "valueFixedPlaceholder": { ar: "قيمة المبلغ", en: "Fixed Value" },
    "minOrderAmountOptional": { ar: "الحد الأدنى للطلب (اختياري)", en: "Min Order Amount (Optional)" },
    "validityDaysPlaceholder": { ar: "أيام الصلاحية", en: "Validity Days" },
    "create": { ar: "إنشاء", en: "Create" },
    "pleaseEnterTitleAndMessage": { ar: "يرجى إدخال العنوان والرسالة", en: "Please enter title and message" },
    "confirmSend": { ar: "تأكيد الإرسال", en: "Confirm Send" },
    "confirmSendToTarget": { ar: "تأكيد الإرسال إلى الفئة المستهدفة", en: "Confirm send to target" },
    "send": { ar: "إرسال", en: "Send" },
    "notificationSentToCount": { ar: "تم إرسال الإشعار إلى {{count}}", en: "Notification sent to {{count}}" },
    "sendFailed": { ar: "فشل الإرسال", en: "Send Failed" },
    "unknownError": { ar: "خطأ غير معروف", en: "Unknown Error" },
    "allUsers": { ar: "جميع المستخدمين", en: "All Users" },
    "newUsers7Days": { ar: "مستخدمين جدد (7 أيام)", en: "New Users (7 Days)" },
    "inactiveUsers": { ar: "المستخدمين غير النشطين", en: "Inactive Users" },
    "manageNotifications": { ar: "إدارة الإشعارات", en: "Manage Notifications" },
    "sendNewNotification": { ar: "إرسال إشعار جديد", en: "Send New Notification" },
    "title": { ar: "العنوان", en: "Title" },
    "titlePlaceholder": { ar: "أدخل العنوان", en: "Enter title" },
    "message": { ar: "الرسالة", en: "Message" },
    "messagePlaceholder": { ar: "أدخل الرسالة", en: "Enter message" },
    "targetAudience": { ar: "الجمهور المستهدف", en: "Target Audience" },
    "sendNow": { ar: "إرسال الآن", en: "Send Now" },
    "expoNotificationInfo": { ar: "معلومات إشعار إكسبو", en: "Expo Notification Info" },
    "sendingHistory": { ar: "سجل الإرسال", en: "Sending History" },
    "noPreviousHistory": { ar: "لا يوجد سجل سابق", en: "No Previous History" },
    "justNow": { ar: "الآن", en: "Just Now" },
    "sentCount": { ar: "تم الإرسال", en: "Sent Count" },
    "failedCount": { ar: "التي فشلت", en: "Failed Count" },
    "pending": { ar: "قيد الانتظار", en: "Pending" },
    "confirmed": { ar: "مؤكد", en: "Confirmed" },
    "shipped": { ar: "تم الشحن", en: "Shipped" },
    "out_for_delivery": { ar: "في الطريق للتوصيل", en: "Out for Delivery" },
    "delivered": { ar: "تم التوصيل", en: "Delivered" },
    "cancelled": { ar: "ملغي", en: "Cancelled" },
    "failedToLoadOrders": { ar: "فشل تحميل الطلبات", en: "Failed to load orders" },
    "orderStatusUpdated": { ar: "تم تحديث حالة الطلب", en: "Order Status Updated" },
    "failedToUpdateStatus": { ar: "فشل تحديث الحالة", en: "Failed to update status" },
    "whatsappOrderMsg": { ar: "رسالة طلب الواتساب", en: "WhatsApp Order Message" },
    "item": { ar: "عنصر", en: "Item" },
    "moreProducts": { ar: "المزيد من المنتجات", en: "More Products" },
    "cityDistribution": { ar: "توزيع المدن", en: "City Distribution" },
    "noOrdersYet": { ar: "لا توجد طلبات بعد", en: "No Orders Yet" },
    "dailyPerformance": { ar: "الأداء اليومي", en: "Daily Performance" },
    "noData": { ar: "لا توجد بيانات", en: "No Data" },
    "ordersThisWeek": { ar: "طلبات هذا الأسبوع", en: "Orders This Week" },
    "weeklyRevenue": { ar: "الإيرادات الأسبوعية", en: "Weekly Revenue" },
    "orderCenter": { ar: "مركز الطلبات", en: "Order Center" },
    "searchOrdersPlaceholder": { ar: "البحث في الطلبات...", en: "Search orders..." },
    "hello": { ar: "مرحباً", en: "Hello" },
    "admin": { ar: "المدير", en: "Admin" },
    "storeActivityMonth": { ar: "نشاط المتجر هذا الشهر", en: "Store Activity This Month" },
    "localNotif": { ar: "إشعار محلي", en: "Local Notif" },
    "localNotifDesc": { ar: "وصف الإشعار المحلي", en: "Local Notif Desc" },
    "remoteNotif": { ar: "إشعار عن بعد", en: "Remote Notif" },
    "remoteNotifDesc": { ar: "وصف الإشعار عن بعد", en: "Remote Notif Desc" },
    "pushTestTitle": { ar: "اختبار إشعار التنبيه", en: "Push Test Title" },
    "pushTestMsg": { ar: "رسالة اختبار الإشعار", en: "Push Test Message" },
    "sentSuccessfully": { ar: "تم الإرسال بنجاح", en: "Sent Successfully" },
    "sentSuccessfullyDesc": { ar: "تم إرسال الإشعار بنجاح", en: "Notification sent successfully" },
    "unexpectedError": { ar: "خطأ غير متوقع", en: "Unexpected Error" },
    "avatarFallback": { ar: "صورة رمزية بديلة", en: "Avatar Fallback" },
    "loadingData": { ar: "جاري تحميل البيانات", en: "Loading Data" },
    "totalRevenue": { ar: "إجمالي الإيرادات", en: "Total Revenue" },
    "thisMonth": { ar: "هذا الشهر", en: "This Month" },
    "last7Days": { ar: "آخر 7 أيام", en: "Last 7 Days" },
    "order": { ar: "طلب", en: "Order" },
    "customer": { ar: "عميل", en: "Customer" },
    "newCustomer": { ar: "عميل جديد", en: "New Customer" },
    "newCustomers": { ar: "عملاء جدد", en: "New Customers" },
    "today": { ar: "اليوم", en: "Today" },
    "orderStatus": { ar: "حالة الطلب", en: "Order Status" },
    "orderTrends": { ar: "اتجاهات الطلبات", en: "Order Trends" },
    "salesByCategory": { ar: "المبيعات حسب الفئة", en: "Sales by Category" },
    "topCategories": { ar: "أفضل الفئات", en: "Top Categories" },
    "noSalesData": { ar: "لا توجد بيانات للمبيعات", en: "No Sales Data" },
    "newOrders": { ar: "طلبات جديدة", en: "New Orders" },
    "awaitingConfirmation": { ar: "في انتظار التأكيد", en: "Awaiting Confirmation" },
    "onTheWay": { ar: "في الطريق", en: "On the Way" },
    "storeManagement": { ar: "إدارة المتجر", en: "Store Management" },
    "profits": { ar: "الأرباح", en: "Profits" },
    "settings": { ar: "الإعدادات", en: "Settings" },
    "coupons": { ar: "الكوبونات", en: "Coupons" },
    "recentOrders": { ar: "الطلبات الأخيرة", en: "Recent Orders" },
    "noRecentOrders": { ar: "لا توجد طلبات أخيرًا", en: "No Recent Orders" },
    "deleteProduct": { ar: "حذف المنتج", en: "Delete Product" },
    "confirmDeleteProduct": { ar: "هل أنت متأكد من حذف هذا المنتج؟", en: "Are you sure you want to delete this product?" },
    "productDeleted": { ar: "تم حذف المنتج", en: "Product Deleted" },
    "deleteFailed": { ar: "فشل الحذف", en: "Delete Failed" },
    "lowStock": { ar: "مخزون منخفض", en: "Low Stock" },
    "available": { ar: "متوفر", en: "Available" },
    "draft": { ar: "مسودة", en: "Draft" },
    "needsAttention": { ar: "يحتاج للاهتمام", en: "Needs Attention" },
    "productsManagement": { ar: "إدارة المنتجات", en: "Products Management" },
    "searchProduct": { ar: "البحث عن منتج...", en: "Search Product..." },
    "general": { ar: "عام", en: "General" },
    "errorAddingExpense": { ar: "خطأ في إضافة المصروف", en: "Error adding expense" },
    "revenueAndExpenses": { ar: "الإيرادات والمصروفات", en: "Revenue and Expenses" },
    "week": { ar: "أسبوع", en: "Week" },
    "month": { ar: "شهر", en: "Month" },
    "year": { ar: "سنة", en: "Year" },
    "totalIncome": { ar: "إجمالي الدخل", en: "Total Income" },
    "orderCountSuffix": { ar: "طلبات", en: "orders" },
    "averageOrderValue": { ar: "متوسط قيمة الطلب", en: "Avg Order Value" },
    "perOrder": { ar: "لكل طلب", en: "Per Order" },
    "netProfitActual": { ar: "الربح الصافي الفعلي", en: "Actual Net Profit" },
    "cogsEstimate": { ar: "تكلفة المبيعات المقدرة", en: "Estimated COGS" },
    "expenses": { ar: "المصروفات", en: "Expenses" },
    "expensesHistory": { ar: "سجل المصروفات", en: "Expenses History" },
    "add": { ar: "إضافة", en: "Add" },
    "noExpensesRecorded": { ar: "لا توجد مصروفات مسجلة", en: "No Expenses Recorded" },
    "topPerformingProducts": { ar: "أفضل المنتجات أداءً", en: "Top Performing Products" },
    "salesCountSuffix": { ar: "مبيعات", en: "sales" },
    "addNewExpense": { ar: "إضافة مصروف جديد", en: "Add New Expense" },
    "expenseTitle": { ar: "عنوان المصروف", en: "Expense Title" },
    "expenseTitlePlaceholder": { ar: "أدخل عنوان المصروف", en: "Enter Expense Title" },
    "amountKWD": { ar: "المبلغ", en: "Amount" },
    "deleteComment": { ar: "حذف التعليق", en: "Delete Comment" },
    "updateCommentStatus": { ar: "تحديث حالة التعليق", en: "Update Comment Status" },
    "deleteCommentConfirm": { ar: "هل أنت متأكد من حذف هذا التعليق؟", en: "Are you sure you want to delete this comment?" },
    "changeCommentStatus": { ar: "تغيير حالة التعليق", en: "Change Comment Status" },
    "confirm": { ar: "تأكيد", en: "Confirm" },
    "actionFailed": { ar: "فشلت العملية", en: "Action Failed" },
    "anonymousUser": { ar: "مستخدم مجهول", en: "Anonymous User" },
    "locale": { ar: "ar", en: "en" },
    "unknownDate": { ar: "تاريخ غير معروف", en: "Unknown Date" },
    "viewProduct": { ar: "عرض المنتج", en: "View Product" },
    "manageReviews": { ar: "إدارة التعليقات", en: "Manage Reviews" },
    "✅ تم": { ar: "✅ تم", en: "✅ Done" },
    "تسجيل الخروج": { ar: "تسجيل الخروج", en: "Logout" },
    "حذف المشرف": { ar: "حذف المشرف", en: "Delete Admin" },
    "حذف الكوبون": { ar: "حذف الكوبون", en: "Delete Coupon" },
    "تم": { ar: "تم", en: "Done" },
    "حذف الدولة": { ar: "حذف الدولة", en: "Delete Country" },
    "تم بنجاح": { ar: "تم بنجاح", en: "Successfully Completed" },
    "خطأ": { ar: "يوجد خطأ", en: "Error" },
    "نجاح": { ar: "نجح الإجراء", en: "Success" },
    "تنبيه": { ar: "تحذير للمستخدم", en: "Alert" }
};

const keysFile = JSON.parse(fs.readFileSync('keys_to_translate.json'));

keysFile.forEach(key => {
    if (translations[key]) {
        arJson[key] = translations[key].ar || key;
        enJson[key] = translations[key].en || key;
    }
});

// Write to files
fs.writeFileSync(arPath, JSON.stringify(arJson, null, 4));
fs.writeFileSync(enPath, JSON.stringify(enJson, null, 4));

console.log('Translations successfully updated in json files.');
